//
//  include.h
//  mulle-mmap
//
//  Copyright (c) 2022 Nat! - Mulle kybernetiK.
//  All rights reserved.
//
//
//  Redistribution and use in source and binary forms, with or without
//  modification, are permitted provided that the following conditions are met:
//
//  Redistributions of source code must retain the above copyright notice, this
//  list of conditions and the following disclaimer.
//
//  Redistributions in binary form must reproduce the above copyright notice,
//  this list of conditions and the following disclaimer in the documentation
//  and/or other materials provided with the distribution.
//
//  Neither the name of Mulle kybernetiK nor the names of its contributors
//  may be used to endorse or promote products derived from this software
//  without specific prior written permission.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
//  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
//  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
//  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
//  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
//  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
//  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
//  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
//  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
//  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
//  POSSIBILITY OF SUCH DAMAGE.
//
#ifndef mulle__mmap_include_h__
#define mulle__mmap_include_h__

/* DO:    #include this files in public headers.

   DONT:  #include this files in private headers.
          #include this file directly in sources.
          #import this file anywhere (except in import.h)
 */


/* This is a central include file to keep dependencies out of the library
   C files. It is usually included by .h files only.

   As the name "include.h" is standardized across mulle-sde projects,
   .c and .h files are now  motile. They can be moved to other projects and
   don't need to be edited.

   If you delete it, it will not be regenerated.
*/

/*
 * Include the header file generated by mulle-sde reflect.
 */

#include "_mulle-mmap-include.h"

// this is for WIN32: specify global non-inlined functions and variables
// like this (can not be declared inside functions!)
//
// .h:
// #include "include.h"
// MULLE__MMAP_GLOBAL char *   aGlobalString;
// MULLE__MMAP_GLOBAL void     aGlobalFunction( void);
//
// .c:
// #include "include-private.h"
// MULLE__MMAP_GLOBAL_VAR
// char *  aGlobalString = "VfL Bochum 1848";
// MULLE__MMAP_GLOBAL
// void   aGlobalFunction( void) {}
//
#ifndef MULLE__MMAP_GLOBAL
# ifdef MULLE__MMAP_BUILD
#  define MULLE__MMAP_GLOBAL       MULLE_C_GLOBAL
#  define MULLE__MMAP_GLOBAL_VAR   MULLE_C_GLOBAL
# else
#  if defined( MULLE__MMAP_INCLUDE_DYNAMIC) || (defined( MULLE_INCLUDE_DYNAMIC) && ! defined( MULLE__MMAP_INCLUDE_STATIC))
#   define MULLE__MMAP_GLOBAL      MULLE_C_GLOBAL
#  else
#   define MULLE__MMAP_GLOBAL      extern
#  endif
# endif
# define MULLE__MMAP_GLOBAL_VAR    MULLE_C_GLOBAL
#endif
/* You can add some more include statements here */

#endif
