/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_mmap_include_h__
#define _mulle_mmap_include_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-allocator`
// (Use 974D6E5B-5644-44A3-B15B-DB2B66107A03 instead of mulle-allocator, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-allocator no-header`
//    rename              : `mulle-sde dependency|library set mulle-allocator include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-allocator <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-allocator [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-allocator [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-allocator [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-allocator no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-allocator/mulle-allocator.h>   // mulle-allocator

#endif
